RAILS-BLOG/config/routes.rb
Rails.application.routes.draw do

  root to: 'posts#index'

  get '/login' => 'admin/sessions#new'
  get '/logout' => 'admin/sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do 
    resources :settings, only: [:new,:create,:edit,:update]
    resources :dashboard, only: [:index]
    resources :notifications, only: [:index,:destroy]
    resources :messages, only: [:index,:show,:update,:destroy]
    resources :visitors, only: [:index,:destroy]
    resources :comments, only: [:index,:update,:destroy]
    resources :tags, except: [:index]
    resources :posts
    resources :sessions, only: [:new,:create,:destroy]
    resources :moderators, only: [:index,:edit,:update]
  end
  resources :posts, only: [:index,:show]
  resources :messages, only: [:new ,:create]
  resources :comments, only:[:create]
  match 'dismiss_all_notifications', to: 'admin/notifications#delete_all', via: :delete
end

RAILS-BLOG/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :visitor
  has_many :notifications, as: :notifiable, dependent: :destroy

  validates :message, presence: true
  scope :approved, -> { where status: true}

  after_save :notify

  def notify
    notifications.build.save
  end
end

RAILS-BLOG/app/models/message.rb
class Message < ApplicationRecord
  belongs_to :visitor
  
  validates :content, presence: true

  def mark_read
    update(status: true) if status == false
  end
end

RAILS-BLOG/app/models/moderator.rb
class Moderator < ApplicationRecord
  has_secure_password
  has_many :posts
  validates :fullname, presence: true
  validates :username, presence: true, format: {with: /@/, message: 'is not valid'}
  validates :password, presence: true
end

RAILS-BLOG/app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :notifiable, polymorphic: true
end

RAILS-BLOG/app/models/post.rb
class Post < ApplicationRecord
  belongs_to :moderator
  has_many :comments, dependent: :destroy
  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags

  validates :title, presence: true
  validates :content, presence: true
  scope :published, -> {where publish: true}

  def self.filter_by_tags param_tag
    includes(:tags).where(publish: true, tags: {name: param_tag}).order(id: :desc)
  end
end

RAILS-BLOG/app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

RAILS-BLOG/app/models/setting.rb
class Setting < ApplicationRecord
  def self.site_name
    Setting.first.try(:site_name)
  end
end

RAILS-BLOG/app/models/tag.rb
class Tag < ApplicationRecord
  has_many :posts,  through: :post_tags

  validates :name, presence: true
  def in_use?
    if PostTag.exists?(tag_id: self.id)
      "In Use"
    else
      "Not In Use"
    end
  end
end

RAILS-BLOG/app/models/visitor.rb
class Visitor < ApplicationRecord
  has_many :notifications, as: :notifiable, dependent: :destroy
  has_many :messages,dependent: :destroy
  has_many :comments,dependent: :destroy

  validates :fullname, presence: true
  validates :email, format: { with: /@/, message: 'is not valid' }

  def is_active?
    if (Message.exists?(visitor_id: self.id) || Comment.exists?(visitor_id: self.id))
      'Active'
    else
      'In Active'
    end
  end
  
  accepts_nested_attributes_for :comments
  accepts_nested_attributes_for :messages

  after_save :notify

  def notify
    notifications.build.save
  end
end

RAILS-BLOG/app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::ApplicationController
  
  def index
    @posts = Post.last 5
    @comments = Comment.last 5
    @visitors = Visitor.last 5
  end
end

RAILS-BLOG/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  
end

RAILS-BLOG/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def create
    if visitor.save
      flash[:notice] = "Successfully created new comment"
    else
      set_visitor_sessions
      flash[:alert] = "Problem creating your comment."
    end
    redirect_to :back
  end                         

  private

  def visitor_comments_params
    params.require(:visitor).permit(:fullname,:email,:comments_attributes => [:message,:post_id])
  end

  def visitor
    @visitor ||= VisitorCommentService.new(visitor_comments_params).visitor
  end
  
  def set_visitor_sessions
    session[:visitor_errors] = visitor.errors.full_messages
    session[:visitor_params] = visitor_comments_params
  end
end

RAILS-BLOG/app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
    @visitor_message = Visitor.new(messages: [Message.new])
  end

  def create
    if visitor.save
      flash[:notice] = "Successfully sent your message."
      redirect_to :back
    else
      @visitor_message = visitor
      render :new
    end
  end

  private

  def strong_params
    params.require(:visitor).permit(:fullname,:email,message_attributes: [:content])
  end

  def visitor
    @visitor||= VisitorMessageService.new(strong_params).visitor
  end
end

RAILS-BLOG/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  after_filter :clear_sessions, only: [:show]
  def index
    if params[:tag]
      @posts = Post.filter_by_tags(params[:tag]).page(params[:page]).per(Setting.first.posts_per_page)
    else
      @posts = Post.published.order(id: :desc).page(params[:page]).per(Setting.first.posts_per_page)
    end
  end

  def show
    @post = Post.find(params[:id])
    @visitor_comment = visitor_comment
  end

  def clear_sessions
    [:visitor_errors].each { |k| session.delete(k) }
  end

  def visitor_comment
    if session[:visitor_errors]
      VisitorCommentService.new(session[:visitor_params]).visitor
    else
      Visitor.new(comments: [Comment.new])
    end
  end
end

RAILS-BLOG/app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

RAILS-BLOG/app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

RAILS-BLOG/app/helpers/admin/messages_helper.rb
module Admin::MessagesHelper
  def message_weight message
    message.status == false ? 'font-weight:bold' : 'font-weight:normal'
  end
end

RAILS-BLOG/app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

RAILS-BLOG/app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

RAILS-BLOG/app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

RAILS-BLOG/app/helpers/application_helper.rb
module ApplicationHelper
  def status_converter(status,truthy: nil, falsey: nil)
    if status
      truthy
    else
      falsey
    end
  end

  def time_ago time
    "#{time_ago_in_words(time)} ago"
  end

  def double_digit_number n
    '%02d' % n
  end

end

RAILS-BLOG/app/helpers/messages_helper.rb
module MessagesHelper
end

RAILS-BLOG/app/views/admin/dashboard/index.html.erb
<h1>Dashboard</h1>

<h2>Post</h2>

<%= link_to 'Create New Post', new_admin_post_path %></br>
<%= link_to 'List Posts', admin_posts_path %></br>

<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>title</th>
      <th>replies</th>
      <th>date</th>
      <th>actions</th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post|%>
      <tr>
        <td><%= truncate(post.title, length: 40, separator: '')%></td>
        <td><%= post.comments.count %></td>
        <td><%= time_ago post.created_at%></td>
        <td>
          <%= link_to 'Edit', edit_admin_post_path(post) %>
          <%= link_to 'View', admin_post_path(post) %>
          <%= link_to 'Delete', admin_post_path(post), method: :delete, data: {confirm: 'Are you sure?'} %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<h2>Comments</h2>

<%= link_to 'List Comments', admin_comments_path %>

<% @comments.each do |comment|%>
  <p><%= comment.visitor.fullname %></p>
  <p><%= truncate(comment.message, length: 120, separator: '')%></p>
  <p><%= time_ago comment.created_at%></p>
  <hr>
<% end %>

<h2>Visitors</h2>
<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>Index</th>
      <th>FullName</th>
      <th>Email</th>
      <th>Created</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @visitors.each_with_index do |visitor, index|%>
      <tr>
        <td><%= index + 1 %></td>
        <td><%= visitor.fullname%></td>
        <td><%= visitor.email %></td>
        <td><%= time_ago visitor.created_at%></td>
        <td>
          <%= link_to 'Delete', admin_visitor_path(visitor), method: :delete, data: {confirm: 'Are you sure?'} %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>